# Generated by Django 5.1.3 on 2024-11-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_alter_lease_driving_license_alter_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
