# Generated by Django 5.1.3 on 2024-11-08 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_lease_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='driving_licenses'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='introduction_letter',
            field=models.FileField(blank=True, null=True, upload_to='introduction_letters'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='national_ids'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='next_of_kin',
            field=models.FileField(blank=True, null=True, upload_to='next_of_kin_ids'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
